# Generated by Django 5.2.16 on 2026-09-15 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0065_historicaltheater_theater_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltheater',
            name='location',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='historicaltheater',
            name='production',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='historicaltheater',
            name='venue',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='theater',
            name='location',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='theater',
            name='production',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='theater',
            name='venue',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
