# Generated by Django 5.2.16 on 2026-09-15 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0067_remove_item_app_item_source_valid_alter_item_source_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='stage_artwork',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
