# Generated by Django 5.2.16 on 2026-09-15 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0068_item_stage_artwork'),
    ]

    operations = [
        migrations.CreateModel(
            name='StageRedirect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias_id', models.CharField(max_length=36, unique=True)),
                ('canonical_id', models.CharField(max_length=36)),
                ('revision', models.PositiveBigIntegerField()),
                ('observed_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
